server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://${MYSQL_HOST:localhost}:5432/shinybank
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          schema-generation:
            scripts:
              action: drop-and-create
              create-source: metadata
              drop-source: metadata
              create-target: conf/db/create-schema.sql
              drop-target: conf/db/drop-schema.sql
